/**
 * Builds the text of the macOS `.app` bundle: the launcher script and the
 * Info.plist.
 *
 * Pure string functions, kept separate from `make-app.ts` so they can be tested
 * without a Mac. Nothing here touches the filesystem or shells out.
 *
 * The launcher is shell because a `.app` executable has to be. It is generated
 * rather than committed so the repo path can be baked in: an app launched from
 * Finder starts in `/`, not the project directory.
 */

export const APP_NAME = "Studyapp";
export const BUNDLE_ID = "local.studyapp.launcher";

/** The largest square image in the repo. There is no 1024 and no .icns. */
export const ICON_SOURCE = "apps/next/public/android-chrome-512x512.png";

/** Sizes an .iconset needs. 512@2x is upscaled; no 1024 source exists. */
export const ICONSET_SIZES: { name: string; px: number }[] = [
  { name: "icon_16x16.png", px: 16 },
  { name: "icon_16x16@2x.png", px: 32 },
  { name: "icon_32x32.png", px: 32 },
  { name: "icon_32x32@2x.png", px: 64 },
  { name: "icon_128x128.png", px: 128 },
  { name: "icon_128x128@2x.png", px: 256 },
  { name: "icon_256x256.png", px: 256 },
  { name: "icon_256x256@2x.png", px: 512 },
  { name: "icon_512x512.png", px: 512 },
  { name: "icon_512x512@2x.png", px: 1024 },
];

export const infoPlist = (): string => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>studyapp</string>
  <key>CFBundleIconFile</key><string>studyapp</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict>
</plist>
`;

/**
 * Shell single-quote escaping: close the quote, insert an escaped quote, reopen.
 * Repo paths can contain spaces and apostrophes, and the launcher embeds one.
 */
export const shellQuote = (value: string): string =>
  `'${value.replace(/'/g, `'\\''`)}'`;

export interface LauncherOptions {
  /** Absolute path to the repo, baked in because Finder launches from "/". */
  repoPath: string;
  /** The port .env is pinned to. Drift here breaks auth, so it is not dynamic. */
  port?: number;
}

export const launcherScript = ({
  repoPath,
  port = 3000,
}: LauncherOptions): string => {
  const repo = shellQuote(repoPath);
  const url = `http://localhost:${port}`;

  return `#!/bin/bash
# Generated by scripts/make-app.ts. Re-run "bun run make:app" after moving the
# repo: the path below is baked in, because an app launched from Finder starts
# in "/" and inherits none of the shell's environment.
set -uo pipefail

REPO=${repo}
PORT=${port}
URL="${url}"
APP_SUPPORT="$HOME/Library/Application Support/${APP_NAME}"
CHROME_PROFILE="$APP_SUPPORT/chrome"
LOG_DIR="$HOME/Library/Logs/${APP_NAME}"
LOG="$LOG_DIR/launcher.log"

# Finder gives a minimal PATH, so bun, mysql and node are not on it. Name the
# Homebrew locations explicitly rather than hoping a profile gets sourced.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

mkdir -p "$LOG_DIR" "$CHROME_PROFILE"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >>"$LOG"; }

# Nothing is visible when an app fails from Finder, so every fatal path has to
# say something on screen.
fail() {
  log "FATAL: $1"
  # The message is passed as an argv item rather than interpolated into the
  # AppleScript source, so an apostrophe or quote in it cannot break the script.
  /usr/bin/osascript -e 'on run argv
    display dialog (item 1 of argv) with title "${APP_NAME}" buttons {"OK"} default button "OK" with icon caution
  end run' "$1

Log: $LOG" >/dev/null 2>&1
  exit 1
}

# Does the port answer as a web server? Distinguishes "our app is running" from
# "something else is squatting on the port", which matters because next dev
# silently moves to the next free port when this one is taken, while .env still
# points at this one.
responds() {
  curl -fsS -o /dev/null --max-time 2 "$URL/api/health" 2>/dev/null && return 0
  curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
}

port_held() {
  lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1
}

open_window() {
  local chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  if [ ! -x "$chrome" ]; then
    log "Chrome not found, falling back to the default browser"
    open "$URL"
    return 1
  fi
  log "opening app window"
  "$chrome" --app="$URL" --user-data-dir="$CHROME_PROFILE" \\
    --no-first-run --no-default-browser-check >>"$LOG" 2>&1
}

log "--- launch ---"
cd "$REPO" || fail "Cannot find the project at $REPO. Re-run 'bun run make:app'."

# Already running? Focus it rather than starting a second server.
if port_held; then
  if responds; then
    log "already running; opening a window against the existing server"
    open_window
    exit 0
  fi
  fail "Port $PORT is in use by something that is not ${APP_NAME}. Quit it and try again."
fi

[ -f "$REPO/.env" ] || fail "No .env found. Run 'bun run setup:local' in the project folder first."

# MySQL. mysql.server is session-scoped, unlike brew services, which would add
# a permanent login item.
if ! mysqladmin ping --silent >/dev/null 2>&1; then
  log "MySQL not responding; starting it"
  mysql.server start >>"$LOG" 2>&1
  sleep 2
  mysqladmin ping --silent >/dev/null 2>&1 || fail "Could not start MySQL. Try 'mysql.server start' in a terminal."
fi

# Own process group, so the whole tree can be signalled on quit. bun dev is
# bun -> dotenv -> turbo -> sh -> next dev -> workers, and SIGTERM to the top
# pid alone leaves workers holding the port.
log "starting the server"
set -m
bun dev --no-daemon >>"$LOG" 2>&1 &
SERVER_PGID=$!
set +m

stop_server() {
  if [ -n "\${SERVER_PGID:-}" ]; then
    log "stopping the server (pgid $SERVER_PGID)"
    kill -TERM -"$SERVER_PGID" 2>/dev/null
    for _ in $(seq 1 20); do
      port_held || break
      sleep 0.5
    done
    port_held && kill -KILL -"$SERVER_PGID" 2>/dev/null
  fi
}
trap stop_server EXIT INT TERM

# next dev compiles on demand, so answering the port is the right signal; it
# queues early requests rather than rejecting them.
log "waiting for the server"
READY=""
for _ in $(seq 1 120); do
  if responds; then READY=1; break; fi
  kill -0 "$SERVER_PGID" 2>/dev/null || break
  sleep 1
done

[ -n "$READY" ] || fail "The server did not start within two minutes. See the log for why."

log "ready"
open_window
log "window closed"
`;
};
